// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StateContextProvider from "./context/StateContext";
import GotoTop from "./components/Ui/GotoTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FoodForethought",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="nohemi">
        <StateContextProvider>{children}
          <GotoTop/>
        </StateContextProvider>
      </body>
    </html>
  );
}
